// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gGL3CledTNLNJkFZujE2PCDtgj7n-hc',
    appId: '1:798363038845:web:87b57db22f821560b96d14',
    messagingSenderId: '798363038845',
    projectId: 'darija-flutte',
    authDomain: 'darija-flutte.firebaseapp.com',
    storageBucket: 'darija-flutte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gQcbQtbU6mSc8jk2LaSsfMvsbz_JlOA',
    appId: '1:798363038845:android:fd24d731f255cdfcb96d14',
    messagingSenderId: '798363038845',
    projectId: 'darija-flutte',
    storageBucket: 'darija-flutte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmanPrRi94Nlovyl0GuvDoBUVwvgsmclQ',
    appId: '1:798363038845:ios:ef7b05c8fda72cf0b96d14',
    messagingSenderId: '798363038845',
    projectId: 'darija-flutte',
    storageBucket: 'darija-flutte.firebasestorage.app',
    iosBundleId: 'com.example.darijaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmanPrRi94Nlovyl0GuvDoBUVwvgsmclQ',
    appId: '1:798363038845:ios:ef7b05c8fda72cf0b96d14',
    messagingSenderId: '798363038845',
    projectId: 'darija-flutte',
    storageBucket: 'darija-flutte.firebasestorage.app',
    iosBundleId: 'com.example.darijaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6gGL3CledTNLNJkFZujE2PCDtgj7n-hc',
    appId: '1:798363038845:web:911e155aa3724193b96d14',
    messagingSenderId: '798363038845',
    projectId: 'darija-flutte',
    authDomain: 'darija-flutte.firebaseapp.com',
    storageBucket: 'darija-flutte.firebasestorage.app',
  );
}
